CREATE TABLE IF NOT EXISTS easygo_business_object (
                                                      id bigint PRIMARY KEY AUTO_INCREMENT COMMENT '业务对象ID',
                                                      name varchar(100) NOT NULL COMMENT '业务对象名称',
                                                      bo_name varchar(100) NOT NULL COMMENT '业务对象实体名称',
                                                      table_name varchar(100) NOT NULL COMMENT '业务对象对应表名',
                                                      datasource varchar(2000) NOT NULL COMMENT '数据来源',
                                                      sort int NOT NULL DEFAULT 0 COMMENT '显示顺序',
                                                      java_path bigint NOT NULL DEFAULT 0 COMMENT '后端代码路径',
                                                      vue_path varchar(200) NULL DEFAULT '' COMMENT '前端代码路径',
                                                      process_id varchar(36) NULL COMMENT '关联流程定义',
                                                      creator varchar(64) NULL DEFAULT '' COMMENT '创建者',
                                                      create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                      updater varchar(64) NULL DEFAULT '' COMMENT '更新者',
                                                      update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                      deleted bit NOT NULL DEFAULT 0 COMMENT '是否删除'
);
CREATE TABLE IF NOT EXISTS easygo_business_object_method (
                                                             id bigint PRIMARY KEY AUTO_INCREMENT COMMENT '业务对象ID',
                                                             method_name varchar(100) NOT NULL COMMENT '方法名',
                                                             method_desc varchar(100) NOT NULL COMMENT '方法描述',
                                                             bo_id bigint NOT NULL COMMENT '业务对象ID',
                                                             url varchar(200) NOT NULL COMMENT 'url路径',
                                                             icon varchar(100) NULL DEFAULT '#' COMMENT '图标',
                                                             permission varchar(100) NOT NULL DEFAULT '' COMMENT '权限标识',
                                                             sort int NOT NULL DEFAULT 0 COMMENT '显示顺序',
                                                             creator varchar(64) NULL DEFAULT '' COMMENT '创建者',
                                                             create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                             updater varchar(64) NULL DEFAULT '' COMMENT '更新者',
                                                             update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                             deleted bit NOT NULL DEFAULT 0 COMMENT '是否删除'
);
CREATE TABLE IF NOT EXISTS easygo_business_object_prop (
                                                           id bigint PRIMARY KEY AUTO_INCREMENT COMMENT '业务对象ID',
                                                           name varchar(100) NOT NULL COMMENT '业务属性名称',
                                                           show_name varchar(100) NOT NULL COMMENT '业务属性前端展示名称',
                                                           bo_id bigint NOT NULL COMMENT '业务对象ID',
                                                           column_name varchar(100) NOT NULL COMMENT '业务属性对应字段名',
                                                           search_help_id varchar(36) NOT NULL COMMENT '搜索帮助ID',
                                                           dict_id varchar(36) NOT NULL COMMENT '字典ID',
                                                           ui_type varchar(50) NULL COMMENT '组件类型',
                                                           is_cond bit NULL DEFAULT 0 COMMENT '是否作为查询条件',
                                                           form_show bit NOT NULL DEFAULT 1 COMMENT '是否在表单中展示',
                                                           grid_show bit NOT NULL DEFAULT 1 COMMENT '是否在列表中展示',
                                                           form_row int NULL COMMENT '表单行位置',
                                                           form_col int NULL COMMENT '表单列位置',
                                                           grid_col int NULL COMMENT '列表中位置',
                                                           type char(2) NOT NULL COMMENT '属性类型：10：数据库字段；20：子表',
                                                           sub_bo_id bigint NOT NULL COMMENT '子业务对象ID',
                                                           sort int NOT NULL DEFAULT 0 COMMENT '显示顺序',
                                                           creator varchar(64) NULL DEFAULT '' COMMENT '创建者',
                                                           create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                           updater varchar(64) NULL DEFAULT '' COMMENT '更新者',
                                                           update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                           deleted bit NOT NULL DEFAULT 0 COMMENT '是否删除'
);